version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - API_HOST=http://backend:5000/
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongodb:27017/apartments
    depends_on:
      - mongodb
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app_network
    # volumes:
    #   - mongo_data:/data/db

networks:
  app_network:
    driver: bridge

# volumes:
#   mongo_data:
#     driver: local